### 5주차. 벡터와 공간
#### 1. 벡터의 표현  numpy.array([#,#])
1) 크기가 (3, )인 1차원 배열의 표현

In [2]:
import numpy as np

x = np.array([1, 2, 3]) 
print(x)

[1 2 3]


2) 크기가 (1, 3)인 2차원 배열의 표현(행 벡터)

In [2]:
u = np.array([[1, 2, 3]])  
print(u)

[[1 2 3]]


3) 크기가 (3, 1)인 2차원 배열의 표현(열 벡터)

In [3]:
v = np.array([[1], [2], [3]])
print(v)

[[1]
 [2]
 [3]]


4) 크기가 (3, 2)인 2차원 배열의 표현(열 벡터)

In [9]:
w = np.array([[1, 2], [2, 2], [3, 2]])
print(w)

[[1 2]
 [2 2]
 [3 2]]


4) 크기가 (3, 3, 2)인 3차원 배열의 표현(열 벡터)

In [3]:
y = np.array([[[1, 2], [1, 2], [1, 2]]
              ,[[2, 2], [2, 2], [2, 2]]
             , [[3, 2], [3, 2], [3, 2]]])
print(y)

[[[1 2]
  [1 2]
  [1 2]]

 [[2 2]
  [2 2]
  [2 2]]

 [[3 2]
  [3 2]
  [3 2]]]


#### 2. 특수한 벡터
- 단위벡터  linalg.norm()

In [8]:
import numpy as np
from scipy import linalg

s=np.array([2,3,1])
v_hat01 = s / linalg.norm(s)
print(linalg.norm(s))
print(v_hat01)

3.7416573867739413
[0.53452248 0.80178373 0.26726124]


- 영벡터

In [12]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
s = (2,2,2)
np.zeros(s)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

#### 3. 선형 결합과 선형 독립
- 선형결합 표현

In [16]:
import numpy as np
a = np.array([2,4])
b = np.array([1,6])
c=(4*a)+((-3)*b)
print(c)

[ 5 -2]


#### 4. 부분공간과 부분공간의 기저
- 랭크(rank)  
numpy.linalg.matrix_rank()

In [18]:
import numpy as np
X1 = np.array([[2, 7], [5, 1]])   # 선형독립
np.linalg.matrix_rank(X1)

2

In [19]:
X1 = np.array([[2, 4], [3, 6]])    # 선형종속
np.linalg.matrix_rank(X1)

1