### 1. 벡터의 내적과 외적
#### 1) 벡터의 덧셈

In [15]:
x=[2,5]
y=[3,3]
z=[i+j for i, j in zip(x,y)]
#z=[i+j for i, j in zip([2,5],[3,3])]
print(z)

[5, 8]


In [17]:
# 참고
# list(zip([2,5],[3,3]))
# list(zip([1, 2, 3], [4, 5, 6]))
list(zip([1, 2, 3], [4, 5, 6], [7, 8, 9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [18]:
# NumPy 라이브러리 이용한 덧셈
import numpy as np
u = np.array(x)
v = np.array(y)
w=u+v
print(w)

[5 8]


#### 2) 벡터의 뺄셈

In [11]:
x=[2,5]
y=[3,3]
z=[i-j for i, j in zip(x,y)]
# z=[i-j for i, j in zip([2,5],[3,3])]
print(z)

[-1, 2]


In [12]:
# NumPy 라이브러리 이용한 덧셈
import numpy as np
u = np.array(x)
v = np.array(y)
w=u-v
print(w)

[-1  2]


#### 3) 벡터의 곱셈
3-1) 스칼라의 곱

In [13]:
x=[3,4]
c=8
z=[c*i for i in x]
print(z)

[24, 32]


In [19]:
# NumPy 라이브러리 이용한 간단한 코드

import numpy as np
u = np.array([3,4])
c = 8
# w=u*c
w=8*u
print(w)

[24 32]


3-2) 벡터의 내적

In [23]:
import numpy as np
u = np.array([6,6])
v = np.array([12,0])
# uv = u*v
uv = np.dot(u, v)
print(uv)

72


In [26]:
# numpy.dot()를 이용하여 벡터의 내적

import numpy as np
A = np.arange(1*2*3).reshape((1,2,3))
B1 = np.arange(1*2*3).reshape((1,2,3))
B2 = np.arange(1*2*3).reshape((1,3,2))
B3 = np.arange(1*2*3).reshape((2,1,3))
B4 = np.arange(1*2*3).reshape((2,3,1))
B5 = np.arange(1*2*3).reshape((3,1,2))
B6 = np.arange(1*2*3).reshape((3,2,1))

In [28]:
A

array([[[0, 1, 2],
        [3, 4, 5]]])

In [34]:
B4

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [33]:
np.dot(A,B4) # 결과는 오류가 맞습니다

array([[[[ 5],
         [14]],

        [[14],
         [50]]]])

In [30]:
np.dot(A,B2)

array([[[[10, 13]],

        [[28, 40]]]])

In [5]:
np.dot(A,B4)

array([[[[ 5],
         [14]],

        [[14],
         [50]]]])

3-3) 벡터의 외적

In [36]:
a = (1, 3, 5) 
b = (2, 4, 6)

# 벡터의 외적을 위한 수식을 함수로 구현
def cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
    a[2]*b[0] - a[0]*b[2],
    a[0]*b[1] - a[1]*b[0]]
    return c
cross(a,b)

[-2, 4, -2]

In [37]:
# Numpy 이용한 벡터 외적 계산
import numpy as np      
print(np.cross(a,b))    # cross() 함수 이용한 결과

[-2  4 -2]


#### 4) 벡터의 거리/유사도
4-1) 유클리드 거리(Euclidean distance)

In [38]:
# scipy.spatia 모듈로부터 distance 함수 호출
from scipy.spatial import distance

# 두 점 P1과 P2 명시
p1 = (1, 2, 3)
p2 = (4, 5, 6)

# P1과 P2 사이의 유클리드 거리 계산
d = distance.euclidean(p1, p2)
print("Euclidean distance: ",d)

Euclidean distance:  5.196152422706632


4-2) 맨해튼 거리(Manhattan distance)

In [50]:
# 두 점 P1과 P2 정의
p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])

sum(abs(p2-p1))

9

4-3) 코사인 유사도(Cosine Similarity)

In [4]:
from numpy import dot
from numpy.linalg import norm
import numpy as np

def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

doc1=np.array([1,1,1,1,0])
doc2=np.array([1,0,1,0,1])
doc3=np.array([2,1,1,1,1])

print(cos_sim(doc1, doc2)) #문서1과 문서2의 코사인 유사도
print(cos_sim(doc1, doc3)) #문서1과 문서3의 코사인 유사도
print(cos_sim(doc2, doc3)) #문서2과 문서3의 코사인 유사도

0.5773502691896258
0.8838834764831843
0.8164965809277259


### 2. 행렬변환
#### 1) 역행렬


In [5]:
import numpy as np
A = np.matrix([[1, 0, 0, 0], [2, 1, 0, 0], [3, 0, 1, 0], [4, 0, 0, 1]])
print(np.linalg.inv(A))

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [-3.  0.  1.  0.]
 [-4. -0. -0.  1.]]


#### 2) 전치행렬

In [6]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])